"""Remove column 'other_info'

Revision ID: 2596c393e714
Revises: 63702c74de68
Create Date: 2023-08-18 00:37:22.433936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2596c393e714'
down_revision = '63702c74de68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_model', schema=None) as batch_op:
        batch_op.drop_column('other_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_info', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
