"""Add new column "other_info"

Revision ID: 63702c74de68
Revises: df809245f7d2
Create Date: 2023-08-18 00:35:44.050366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63702c74de68'
down_revision = 'df809245f7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_info', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_model', schema=None) as batch_op:
        batch_op.drop_column('other_info')

    # ### end Alembic commands ###
